### ISSUE TITLE
推荐扫图次数精确度待提升

### ISSUE THREAD

**Issue by Misaka13514** [edwardez/sensei-helper#19]
此程序易用、快速，但是扫图次数精确度与复杂计算对比仍然差距很大（复杂情况可能差 50%，使用 [蔚蓝档案装备刷图升级规划计算本地工具](https://www.gamekee.com/ba/608989.html) 结果作为对比），请问算法有没有继续优化的计划？

**Comment by edwardez** [comment]
我看了一眼，那个用的也是线性规划，如果差距很大可能是因为算法哪里有bug，有差距50%的具体例子吗
这个repo的数据没更新日服最新爆率提升，不知道是不是因为这个

**Comment by Misaka13514** [comment]
是我那个工具开了2倍率这边忘记开了，先关闭这个issue了（

如果后续计算结果差距大的话再发出来
